/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clientes' | '/contato' | '/empresa' | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clientes' | '/contato' | '/empresa' | '/servicos'
  id: '__root__' | '/' | '/clientes' | '/contato' | '/empresa' | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
